PustokApp/Pustok/Models/Author.cs
using Microsoft.Build.Framework;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Pustok.Models
{
    public class Author
    {
        public int Id { get; set; }
        [System.ComponentModel.DataAnnotations.Required]
        [MaxLength(50,ErrorMessage ="Name length can't be more than 50")]
        public string FullName { get; set; }
        public List<Book> Books { get; set; }
    }
}

PustokApp/Pustok/Areas/Admin/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pustok.DAL;
using Pustok.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Pustok.Areas.manage.Controllers
{
    [Area("Admin")]
    public class AuthorController : Controller
    {
        private readonly PustokDbContext _context;

        public AuthorController(PustokDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(int page=1)
        {
            int dataPerPage = 2;
            int totalPage = (int)Math.Ceiling(_context.Authors.Count() / (double)dataPerPage);
            if (page > totalPage)
            {
                return RedirectToAction("Error");
            }
            List<Author> authorList = _context.Authors.Skip((page-1)*dataPerPage).Take(dataPerPage).ToList();


            ViewBag.currentPage = page;
            ViewBag.dataPerPage = dataPerPage;
            ViewBag.totalPage = totalPage;

            return View(authorList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Author author)
        {
            if (author == null)
                return RedirectToAction("Error");

            if (!ModelState.IsValid)
                return View();

            if (_context.Authors.Any(x => x.FullName == author.FullName))
            {
                ModelState.AddModelError("FullName", "This name has already been used");
                return View();
            }

            _context.Authors.Add(author);
            _context.SaveChanges();

            return RedirectToAction("Index");

        }

        public IActionResult Edit(int id)
        {
            Author Author = _context.Authors.FirstOrDefault(x => x.Id == id);
            if (Author == null)
                return RedirectToAction("Error");

            return View(Author);
        }
        [HttpPost]
        public IActionResult Edit(Author author)
        {
            if (!ModelState.IsValid)
                return View();
            if (_context.Authors.Any(x => x.FullName == author.FullName && x.Id != author.Id))
            {
                ModelState.AddModelError("FullName", "This Author allready exists");
                return View();
            }
            if (_context.Authors.FirstOrDefault(x => x.Id == author.Id) == null)
                return RedirectToAction("Error");


            _context.Authors.FirstOrDefault(x => x.Id == author.Id).FullName = author.FullName;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id)
        {
            Author existingAuthor = _context.Authors.Include(x => x.Books).FirstOrDefault(x => x.Id == id);
            if (existingAuthor == null)
                return RedirectToAction("Error");

            return View(existingAuthor);
        }

        [HttpPost]
        public IActionResult Delete(Author Author)
        {
            if (Author == null)
                return RedirectToAction("Error");


            Author existingAuthor = _context.Authors.Include(x => x.Books).FirstOrDefault(x => x.Id == Author.Id);
            if (existingAuthor == null)
                return RedirectToAction("Error");


            if (!existingAuthor.Books.Any(x => x.AuthorId == existingAuthor.Id))
            {
                _context.Authors.Remove(existingAuthor);
                _context.SaveChanges();

            }


            return RedirectToAction("Index");


        }




        public IActionResult Error()
        {
            return View();
        }

    }
}

PustokApp/Pustok/Areas/Admin/Views/Author/Create.cshtml
@{
    ViewData["Title"] = "Create";
}
@model Author



<div class="container mt-5">
    <div class="row justify-content-start">
        <div class="col-md-8">
            <form asp-action="create" method="post">
                <div class="form-group">
                    <label asp-for="FullName">Name</label>
                    <input asp-for="FullName" type="text" class="form-control my-2" placeholder="Enter Author Name">
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary">Add</button>
            </form>
        </div>
    </div>

</div>

PustokApp/Pustok/Areas/Admin/Views/Author/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}
@model Author
<h1>Delete</h1>

<div class="container">

    <table class="table table-striped table-light" id="datatablesSimple">
        <thead>
            <tr>
                <th>Author</th>
                <th>Book Count</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td>@Model.FullName</td>
                <td>@Model.Books.Count</td>
            </tr>
        </tbody>

    </table>

    <form asp-action="delete" method="post" class="form-control">
        <input hidden asp-for="Id" />
        <button type="submit" class="btn btn-danger">Delete</button>
        <a asp-action="index" asp-controller="Author" class="btn btn-primary">Cancel</a>

    </form>


</div>

PustokApp/Pustok/Areas/Admin/Views/Author/Edit.cshtml
@model Author


<div class="container">

    <div class="row col-md-8">
        <form asp-action="edit" method="post" class="form-control">
            <label asp-for="FullName"></label>
            <input asp-for="FullName" type="text" class="form-control my-2" />
            <span class="text-danger" asp-validation-for="FullName"></span><br />
            <button type="submit" class="btn btn-outline-success">Change</button>
        </form>
    </div>
</div>

PustokApp/Pustok/Areas/Admin/Views/Author/Index.cshtml
@{

    int order = (ViewBag.currentPage - 1) * ViewBag.dataPerPage;
    int totalPage = ViewBag.totalPage;
    int currentPage = ViewBag.currentPage;

}

@model List<Author>



<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Tables</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="/admin/dashboard/index">Dashboard</a></li>
            <li class="breadcrumb-item active">Tables</li>
        </ol>
        <div class="card mb-4">
           
        </div>
        <div class="card mb-4">
            <div class="card-header row">
                <div class="col-md-6">
                    <i class="fas fa-table me-1"></i>
                    DataTable Example
                </div>
                <div class="col-md-6 text-end">
                    <a class="btn btn-success" asp-action="create" asp-controller="Author"><i class="fas fa-plus"></i></a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-striped table-light" id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Fullname</th>
                            <th>Action</th>


                        </tr>
                    </thead>
          
                    <tbody>
                        @foreach (var auth in Model)
                        {
                            order++;

                            <tr>
                                <td>@order</td>
                                <td>@auth.FullName</td>
                                <td>
                                    <a class="btn btn-danger" asp-action="delete" asp-controller="Author" asp-route-id="@auth.Id">Delete</a>
                                    <a class="btn btn-primary" asp-action="edit" asp-controller="Author" asp-route-id="@auth.Id">Edit</a>
                                </td>
                            </tr>

                        }
                       
                    </tbody>
                </table>
                <div class="col-12 ">

                    <nav class="m-auto" aria-label="...">
                        <ul class="pagination">

                            <li class="page-item @(currentPage==1? "disabled":"")">
                                <a class="page-link" asp-action="index" asp-controller="Author" asp-route-page="@(currentPage-1)">Previous</a>
                            </li>
                            @{

                                //yazdigim en iyrenc alqoritm ola biler :)


                                if (totalPage <= 5)
                                {
                                    for (int i = 1; i <= totalPage; i++)
                                    {
                                        <li class="page-item @(currentPage == i? "active":"")"><a class="page-link" asp-action="index" asp-controller="Author" asp-route-page="@i">@i</a></li>

                                    }
                                }
                                else if (currentPage < 4 && totalPage <= 5)
                                {
                                    for (int i = 1; i <= totalPage; i++)
                                    {
                                        <li class="page-item @(currentPage == i? "active":"")"><a class="page-link" asp-action="index" asp-controller="Author" asp-route-page="@i">@i</a></li>

                                    }
                                }
                                else if (currentPage < 4)
                                {
                                    for (int i = 1; i <= 5; i++)
                                    {
                                        <li class="page-item @(currentPage == i? "active":"")"><a class="page-link" asp-action="index" asp-controller="Author" asp-route-page="@i">@i</a></li>

                                    }
                                }
                                else if (totalPage >= 5 && currentPage <= totalPage - 2 && currentPage > 2)
                                {
                                    for (int i = currentPage - 2; i <= currentPage + 2; i++)
                                    {
                                        <li class="page-item @(currentPage == i? "active":"")"><a class="page-link " asp-action="index" asp-controller="Author" asp-route-page="@i">@i</a></li>

                                    }
                                }
                                else if (currentPage > totalPage - 2 && currentPage <= totalPage)
                                {
                                    for (int i = totalPage - 4; i <= totalPage; i++)
                                    {
                                        <li class="page-item @(currentPage == i? "active":"")"><a class="page-link" asp-action="index" asp-controller="Author" asp-route-page="@i">@i</a></li>

                                    }
                                }


                            }





                            <li class="page-item @(currentPage==totalPage? "disabled":"")">
                                <a class="page-link" asp-action="index" asp-controller="Author" asp-route-page="@(currentPage+1)">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div>

            </div>
        </div>
    </div>
</main>