PustokApp/Pustok/Models/Genre.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.InteropServices;

namespace Pustok.Models
{
    public class Genre
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "Name length can't be more than 50")]
        public string Name { get; set; }
        public bool isSelected { get; set; }
        public List<Book> Books { get; set; }
    }
}

PustokApp/Pustok/Areas/Admin/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;
using Pustok.DAL;
using Pustok.Migrations;
using Pustok.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Pustok.Areas.manage.Controllers
{
    [Area("Admin")]
    public class GenreController : Controller
    {

        private readonly PustokDbContext _context;

        public GenreController(PustokDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(int page = 1)
        {
            int dataPerPage = 2;
            int totalPage = (int)Math.Ceiling(_context.Genres.Count() / (double)dataPerPage);
            if(page > totalPage)
            {
                return RedirectToAction("Error");
            }

            List<Genre> genreList = _context.Genres.Include(x => x.Books).Skip((page - 1) * dataPerPage).Take(dataPerPage).ToList();



            ViewBag.currentPage = page;
            ViewBag.dataPerPage = dataPerPage;
            ViewBag.totalPage = totalPage;


            return View(genreList);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Genre genre)
        {
            if (genre == null)
                return RedirectToAction("Error");

            if ( !ModelState.IsValid)
                return View();

            if( _context.Genres.Any(x => x.Name == genre.Name))
            {
                ModelState.AddModelError("Name", "This name has already been used");
                return View();
            }
        
                 _context.Genres.Add(genre);
                _context.SaveChanges();

          return RedirectToAction("Index");
           
        }
        public IActionResult Edit(int id)
        {
            Genre genre = _context.Genres.FirstOrDefault(x => x.Id == id);
            if(genre == null)
                return RedirectToAction("Error");

            return View(genre);
        }
        [HttpPost]
        public IActionResult Edit(Genre genre)
        {
            if(!ModelState.IsValid)
                  return View();
            if(_context.Genres.Any(x=> x.Name == genre.Name && x.Id != genre.Id))
            {
                ModelState.AddModelError("Name", "This genre allready exists");
                return View();
            }
            if(_context.Genres.FirstOrDefault(x => x.Id == genre.Id)==null)
                return RedirectToAction("Error");


            _context.Genres.FirstOrDefault(x => x.Id == genre.Id).Name = genre.Name;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            Genre existingGenre = _context.Genres.Include(x=> x.Books).FirstOrDefault(x=> x.Id == id);
            if (existingGenre == null)
                return RedirectToAction("Error");

            return View(existingGenre);
        }

        [HttpPost]
        public IActionResult Delete(Genre genre)
        {
            if (genre == null)
                return RedirectToAction("Error");


            Genre existingGenre = _context.Genres.Include(x=> x.Books).FirstOrDefault(x => x.Id == genre.Id);
            if (existingGenre == null)
                return RedirectToAction("Error");


            if (!existingGenre.Books.Any(x=> x.GenreId == existingGenre.Id))
            { 
                _context.Genres.Remove(existingGenre);
                  _context.SaveChanges();

            }
           

            return RedirectToAction("Index");


        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

PustokApp/Pustok/Areas/Admin/Views/Genre/Create.cshtml
@{
    ViewData["Title"] = "Create";
}
@model Genre



    <div class="container mt-5">
        <div class="row justify-content-start">
            <div class="col-md-8">
                <form asp-action="create" method="post">
                    <div class="form-group">
                        <label asp-for="Name">Name</label>
                        <input asp-for="Name"  type="text" class="form-control my-2" placeholder="Enter Genre Name">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btn btn-primary">Add</button>
                </form>
            </div>
        </div>

    </div>

PustokApp/Pustok/Areas/Admin/Views/Genre/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}
@model Genre

<h1>Delete</h1>

<div class="container">

    <table class="table table-striped table-light" id="datatablesSimple">
        <thead>
            <tr>
                <th>Genre</th>
                <th>Book Count</th>
            </tr>
        </thead>

        <tbody>
           <tr>
                <td>@Model.Name</td>
                <td>@Model.Books.Count</td>
           </tr>
        </tbody>

    </table>

    <form asp-action="delete" method="post" class="form-control" >
        <input  hidden asp-for="Id"/>
        <button type="submit" class="btn btn-danger">Delete</button>
        <a asp-action="index" asp-controller="genre" class="btn btn-primary">Cancel</a>

    </form>


</div>

PustokApp/Pustok/Areas/Admin/Views/Genre/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}
@model Genre

<h1>Edit</h1>

<div class="container">

    <div class="row col-md-8">
        <form asp-action="edit" method="post" class="form-control">
            <label asp-for="Name"></label>
            <input asp-for="Name" type="text" class="form-control my-2" />
            <span class="text-danger"  asp-validation-for="Name"></span><br />
            <button type="submit" class="btn btn-outline-success">Change</button>
        </form>
    </div>
</div>

PustokApp/Pustok/Areas/Admin/Views/Genre/Index.cshtml
@model List<Genre>
@{
    int order = (ViewBag.currentPage - 1) * ViewBag.dataPerPage;
    int totalPage = ViewBag.totalPage;
    int currentPage = ViewBag.currentPage;

}


<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Tables</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="/admin/dashboard/index">Dashboard</a></li>
            <li class="breadcrumb-item active">Tables</li>
        </ol>
        <div class="card mb-4">
        </div>
        <div class="card mb-4">
            <div class="card-header row">
                <div class="col-md-6">
                    <i class="fas fa-table me-1"></i>
                    DataTable Example
                </div>
                <div class="col-md-6 text-end">
                    <a class="btn btn-success" asp-action="create" asp-controller="Genre"><i class="fas fa-plus"></i></a>
                </div>

            </div>
            <div class="card-body">
                <table class="table table-striped table-light" id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>No</th>

                            <th>Genre</th>
                            <th>Book Count</th>
                            <th>Action</th>


                        </tr>
                    </thead>

                    <tbody>

                        @foreach (var genre in Model)
                        {
                            order++;

                            <tr>
                                <td>@order</td>
                                <td>@genre.Name</td>
                                <td>@genre.Books.Count</td>
                                <td>
                                    <a class="btn btn-danger" asp-action="delete" asp-controller="genre" asp-route-id="@genre.Id">Delete</a>
                                    <a class="btn btn-primary" asp-action="edit" asp-controller="genre" asp-route-id="@genre.Id">Edit</a>
                                </td>

                            </tr>

                        }



                    </tbody>
                </table>
                <div class="col-12 ">

                    <nav class="m-auto" aria-label="...">
                        <ul class="pagination">

                            <li class="page-item @(currentPage==1? "disabled":"")">
                                <a class="page-link" asp-action="index" asp-controller="genre" asp-route-page="@(currentPage-1)">Previous</a>
                            </li>
                            @{

                                //yazdigim en iyrenc alqoritm ola biler :)


                                if (totalPage <= 5)
                                {
                                    for (int i = 1; i <= totalPage; i++)
                                    {
                                        <li class="page-item @(currentPage == i? "active":"")"><a class="page-link" asp-action="index" asp-controller="Genre" asp-route-page="@i">@i</a></li>

                                    }
                                }
                                else if(currentPage <4 && totalPage <=5 ){
                                    for (int i = 1; i <= totalPage; i++)
                                    {
                                        <li class="page-item @(currentPage == i? "active":"")"><a class="page-link" asp-action="index" asp-controller="Genre" asp-route-page="@i">@i</a></li>

                                    }
                                }
                                else if (currentPage < 4)
                                {
                                    for (int i = 1; i <= 5; i++)
                                    {
                                        <li class="page-item @(currentPage == i? "active":"")"><a class="page-link" asp-action="index" asp-controller="Genre" asp-route-page="@i">@i</a></li>

                                    }
                                }
                                else if (totalPage >= 5 && currentPage <= totalPage - 2 && currentPage > 2)
                                {
                                    for (int i = currentPage - 2; i <= currentPage + 2; i++)
                                    {
                                        <li class="page-item @(currentPage == i? "active":"")"><a class="page-link " asp-action="index" asp-controller="Genre" asp-route-page="@i">@i</a></li>

                                    }
                                }
                                else if (currentPage > totalPage - 2 && currentPage <= totalPage)
                                {
                                    for (int i = totalPage-4; i <=totalPage; i++)
                                    {
                                        <li class="page-item @(currentPage == i? "active":"")"><a class="page-link" asp-action="index" asp-controller="Genre" asp-route-page="@i">@i</a></li>

                                    }
                                }


                            }





                            <li class="page-item @(currentPage==totalPage? "disabled":"")">
                                <a class="page-link" asp-action="index" asp-controller="genre" asp-route-page="@(currentPage+1)">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div>


            </div>
        </div>
    </div>
</main>